name: Update Translations

on:
#   pull_request:
#     branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
           
      - name: Change Directories
        run: cd kpi/
      - run: cd locale
      - run: git clone https://github.com/kobotoolbox/form-builder-translations.git .
      - run: cd ..
             
      - name: Install Expect
        run: sudo apt-get install expect
        
      - name: Install KPI requirements
        run: sudo pip install -r dependencies/pip/requirements.txt
        
      - name: Intsall translate-toolkit
        run: sudo apt install translate-toolkit
        
      - name: Install Transifex
        run: sudo pip3 install transifex-client
           
      - name: Run make translation po file
        run: sudo ./manage.py makemessages --locale en

      - name: Run json2po
        run: json2po jsapps/compiled/extracted-strings.json locale/en/LC_MESSAGES/djangojs.po
      
      - name: Run Transifex
        with:
            TX_TOKEN: ${{ secrets.TRANSIFEX_API }}
            translations_folder: locale
        uses: docker://sergioisidoro/github-transifex-action:v0.2.0
