name: Update Translations

on:
#   pull_request:
#     branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Change Directories
        run: cd kpi/
        
      - name: Intsall translate-toolkit
        run: sudo apt install translate-toolkit 
        
      - name: Install pip-tools
        run: pip install pip-tools
        
      - name: Install KPI requirements
        run: pip-sync dependencies/pip/requirements.txt
        
      - name: Install Transifex
        run: pip3 install transifex-client
           
      - name: Run make translation po file
        run: ./manage.py makemessages --locale en

      - name: Run json2po
        run: json2po jsapps/compiled/extracted-strings.json locale/en/LC_MESSAGES/djangojs.po
      
      - name: Run Transifex
        run: cd locale
      
      - run: tx push -s
