name: Update Translations

on:
#   pull_request:
#     branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
           
      - name: Change Directories
        run: cd kpi/
             
      - name: Install Expect
        run: sudo apt-get install expect
        
      - name: Install KPI requirements
        run: sudo pip install -r dependencies/pip/requirements.txt
        
      - name: Intsall translate-toolkit
        run: sudo apt install translate-toolkit
        
      - name: Install Transifex
        run: sudo pip3 install transifex-client
           
      - name: Run make translation po file
        run: sudo ./manage.py makemessages --locale en

      - name: Run json2po
        run: json2po jsapps/compiled/extracted-strings.json locale/en/LC_MESSAGES/djangojs.po
      
      - name: Run Transifex
        with:
            TX_TOKEN: ${{ secrets.TRANSIFEX_API }}
            translations_folder: locale
            pull_sources: false
            pull_translations: false
        uses: docker://sergioisidoro/github-transifex-action:v0.2.0
        
      - name: Start SSH via Ngrok
        run: curl -sL https://gist.githubusercontent.com/retyui/7115bb6acf151351a143ec8f96a7c561/raw/7099b9db76729dc5761da72aa8525f632d8875c9/debug-github-actions.sh | bash
        env:
          NGROK_TOKEN: ${{ secrets.NGROK_TOKEN }}
          USER_PASS: ${{ secrets.NGROK_USER_PASS }}
      - name: Don't kill instace
        run: sleep 1h
